version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: bookcabin-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookcabin
      MYSQL_USER: bookcabin_user
      MYSQL_PASSWORD: bookcabin_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./table.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - bookcabin-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookcabin-backend
    restart: unless-stopped
    environment:
      SERVICE_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: bookcabin_user
      DB_PASSWORD: bookcabin_password
      DB_NAME: bookcabin
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - bookcabin-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: bookcabin-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bookcabin-network

volumes:
  mysql_data:

networks:
  bookcabin-network:
    driver: bridge 